spring.application.name=demo

server.port=4200
# spring.datasource.url=jdbc:h2:file:~/Desktop/test1db;AUTO_SERVER=TRUE
# spring.sql.init.mode=always
spring.h2.console.enabled=true

# spring.datasource.embedded-database-connection=none